{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "collapsed": false
   },
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'Part'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-a5ecd4ea2990>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mnumpy\u001b[0m \u001b[1;32mas\u001b[0m \u001b[0mnp\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[1;32mimport\u001b[0m \u001b[0mPart\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[1;32mfrom\u001b[0m \u001b[0mFreeCAD\u001b[0m \u001b[1;32mimport\u001b[0m \u001b[0mBase\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'Part'"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "\n",
    "import Part\n",
    "\n",
    "from FreeCAD import Base \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# create the document\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "eta, theta, phi = 0, np.pi/4., 0\n",
    "\n",
    "r = 3#/np.sqrt(3)\n",
    "\n",
    "H = 28.56 # cylinder height \n",
    "\n",
    "eS = (38.96-28.56)/2.#*np.sqrt(3) #edgespread\n",
    "\n",
    "dd = (H/2 + eS)/np.sqrt(2)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "poslist = [\n",
    "\n",
    "[0, 45, 90, 0, dd, -dd],\n",
    "\n",
    "[0, 45, 0, dd, 0, -dd],\n",
    "\n",
    "[0, 45, -90, 0, -dd, -dd],\n",
    "\n",
    "[0, -45, 0, -dd, 0, -dd],\n",
    "\n",
    "# now the flat part\n",
    "\n",
    "[0, 90, -45, dd, dd, 0],\n",
    "\n",
    "[0, 90, 45, dd, -dd, 0],\n",
    "\n",
    "[0, 90, -45, -dd, -dd, 0],\n",
    "\n",
    "[0, 90, 45, -dd, dd, 0],\n",
    "\n",
    "# finally bottom part\n",
    "\n",
    "[0, 45, 90, 0, -dd,dd],\n",
    "\n",
    "[0, 45, 0, -dd, 0, dd],\n",
    "\n",
    "[0, 45, -90, 0, dd, dd],\n",
    "\n",
    "[0, -45, 0, dd, 0, dd],\n",
    "\n",
    "]\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "doc = FreeCAD.newDocument()\n",
    "\n",
    "fuse = None\n",
    "\n",
    "for pos in poslist:\n",
    "\n",
    "    eta, theta, phi = np.radians(pos[0]), np.radians(pos[1]), np.radians(pos[2])\n",
    "\n",
    "    x0, y0, z0 = pos[3], pos[4], pos[5]\n",
    "\n",
    "    # create the rotation matrix object\n",
    "\n",
    "    myMat = Base.Matrix()\n",
    "\n",
    "    myMat.rotateZ(eta)\n",
    "\n",
    "    myMat.rotateY(theta)\n",
    "\n",
    "    myMat.rotateZ(phi)\n",
    "\n",
    "    myVec = Base.Vector(x0, y0, z0)\n",
    "\n",
    "    # first translate to COM \n",
    "\n",
    "\n",
    "\n",
    "\n",
    "    newcyl = Part.makeCylinder(r,H)\n",
    "\n",
    "    # move to COM\n",
    "\n",
    "    newcyl.translate(Base.Vector(0, 0, -H/2.))\n",
    "\n",
    "    newcyl.transformShape(myMat)\n",
    "\n",
    "    newcyl.translate(myVec)\n",
    "\n",
    "    if fuse is None:\n",
    "\n",
    "        fuse = newcyl\n",
    "\n",
    "    else:\n",
    "\n",
    "        fuse = fuse.fuse(newcyl)\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "newshapeobj = doc.addObject(\"Part::Feature\",\"MyShape\")\n",
    "\n",
    "newshapeobj.Shape = fuse\n",
    "\n",
    "octahedra = fuse.copy()\n",
    "\n",
    "doc_octa = doc\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "collapsed": true
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
